[project]
name = "vuls"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "jinja2>=3.1.6",
  "mkdocs-material>=9.6.14",
  "mkdocs-mermaid2-plugin>=1.2.1",
  "packaging>=25.0",
]

[tool.uv.workspace]
members = ["web-app"]
