"""Add Lynis scan tables

Revision ID: f168cb5dc958
Revises: 20a5eb9f1fd1
Create Date: 2025-06-29 10:48:01.371545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f168cb5dc958'
down_revision: Union[str, Sequence[str], None] = '20a5eb9f1fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
