[ovalDict]
type = "sqlite3"
SQLite3Path = "/vuls/db/oval.sqlite3"

[gost]
type = "sqlite3"
SQLite3Path = "/vuls/db/gost.sqlite3"

[cveDict]
type = "sqlite3"
SQLite3Path = "/vuls/db/cve.sqlite3"

[default]
scanMode = ["offline"]

[servers.icinga2]
host = "icinga2"
scanMode = ["fast"]

[servers.anisette_v3]
host = "anisette-v3"
scanMode = ["fast"]

[servers.retailaware_u16tbpe]
host = "retailaware-u16tbpe"
scanMode = ["fast"]

[servers.thingsboard_cassandra_prod]
host = "thingsboard-cassandra-prod"
scanMode = ["fast"]

[servers.glimpse_paulb_nuc_firebolt_network]
host = "glimpse-paulb-nuc.firebolt.network"
scanMode = ["offline"]
